# SPDX-FileCopyrightText: 2025 Zentrum für Digitale Souveränität der Öffentlichen Verwaltung (ZenDiS) GmbH
# SPDX-License-Identifier: Apache-2.0
---
# The global properties are used to configure multiple charts at once.
global:
  collaborationServerSecret:
    # -- Value of collaboration server secret
    value: ""
    existingSecret:
      # -- Name of existing secret containing collaboration server secret, overrides provided value
      name: ""
      # -- Key where collaboration server secret is stored
      key: "collaborationServerSecret"

  # -- fully qualified domain name of this impress instance
  fqdn: ""

  # -- Define an ImagePullPolicy.
  #
  # Ref.: https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy
  #
  # "IfNotPresent" => The image is pulled only if it is not already present locally.
  # "Always" => Every time the kubelet launches a container, the kubelet queries the container image registry to
  #             resolve the name to an image digest. If the kubelet has a container image with that exact digest cached
  #             locally, the kubelet uses its cached image; otherwise, the kubelet pulls the image with the resolved
  #             digest, and uses that image to launch the container.
  # "Never" => The kubelet does not try fetching the image. If the image is somehow already present locally, the
  #            kubelet attempts to start the container; otherwise, startup fails.
  #
  imagePullPolicy: "IfNotPresent"

  # -- Credentials to fetch images from private registry.
  # Ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  #
  # imagePullSecrets:
  #   - "docker-registry"
  #
  imagePullSecrets: []

  # -- Container registry address.
  imageRegistry: "docker.io"

  # -- TLS secret name
  tlsSecretName: ""

  yProviderApiKey:
    # -- Value of Y Provider API key
    value: ""
    existingSecret:
      # -- Name of existing secret containing Y Provider API key, overrides provided value
      name: ""
      # -- Key where Y Provider API key is stored
      key: "yProviderApiKey"

# backend: {}

# frontend: {}

# y-provider: {}
...
