# SPDX-FileCopyrightText: 2025-2026 Zentrum für Digitale Souveränität der Öffentlichen Verwaltung (ZenDiS) GmbH
# SPDX-License-Identifier: Apache-2.0
---
# -- Additional custom annotations to add to all deployed objects.
additionalAnnotations: {}

# -- Additional custom labels to add to all deployed objects.
additionalLabels: {}

# -- Affinity for pod assignment.
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
# Note: podAffinityPreset, podAntiAffinityPreset, and nodeAffinityPreset will be ignored when it's set.
affinity: {}

# Security Context.
# Ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
containerSecurityContext:
  # -- Enable container privileged escalation.
  allowPrivilegeEscalation: false

  # -- Security capabilities for container.
  capabilities:
    drop:
      - "ALL"

  # -- Enable security context.
  enabled: true

  # -- Run container in privileged mode
  privileged: false

  # -- Process user id.
  runAsUser: 1000

  # -- Process group id.
  runAsGroup: 1000

  # Set Seccomp profile.
  seccompProfile:
    # -- Disallow custom Seccomp profile by setting it to RuntimeDefault.
    type: "RuntimeDefault"

  # -- Mounts the container's root filesystem as read-only.
  readOnlyRootFilesystem: true

  # -- Run container as a user.
  runAsNonRoot: true

# -- Array with extra environment variables to add to containers.
#
# extraEnvVars:
#   - name: FOO
#     value: "bar"
#
extraEnvVars: []

# -- Optionally specify an extra list of additional volumes.
extraVolumes: []

# -- Optionally specify an extra list of additional volumeMounts.
extraVolumeMounts: []

# -- Provide a name to substitute for the full names of resources.
fullnameOverride: ""

# Container image section.
image:
  # -- Container registry address. This setting has higher precedence than global.registry.
  registry: ""

  # -- Container repository string.
  repository: "lasuite/impress-frontend"

  # -- Define an ImagePullPolicy.
  #
  # Ref.: https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy
  #
  # "IfNotPresent" => The image is pulled only if it is not already present locally.
  # "Always" => Every time the kubelet launches a container, the kubelet queries the container image registry to
  #             resolve the name to an image digest. If the kubelet has a container image with that exact digest cached
  #             locally, the kubelet uses its cached image; otherwise, the kubelet pulls the image with the resolved
  #             digest, and uses that image to launch the container.
  # "Never" => The kubelet does not try fetching the image. If the image is somehow already present locally, the
  #            kubelet attempts to start the container; otherwise, startup fails.
  #
  imagePullPolicy: "IfNotPresent"

  # -- Define image tag.
  tag: "v3.3.0@sha256:bb885099bc867ea0a3febdf293542abb6d34474c53150313e1327f6a4c15060f"

# -- Credentials to fetch images from private registry.
# Ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
#
# imagePullSecrets:
#   - "docker-registry"
#
imagePullSecrets: []

# Impress Media Gateway
impressMediaGateway:
  # -- Array with extra environment variables to add to containers.
  #
  # extraEnvVars:
  #   - name: FOO
  #     value: "bar"
  #
  extraEnvVars: []

  # -- Optionally specify an extra list of additional volumeMounts.
  extraVolumeMounts: []

  # Additional container image section for media gateway.
  image:
    # -- Container registry address. This setting has higher precedence than global.registry.
    registry: ""

    # -- Container repository string.
    repository: "nginx"

    # -- Define an ImagePullPolicy.
    #
    # Ref.: https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy
    #
    # "IfNotPresent" => The image is pulled only if it is not already present locally.
    # "Always" => Every time the kubelet launches a container, the kubelet queries the container image registry to
    #             resolve the name to an image digest. If the kubelet has a container image with that exact digest cached
    #             locally, the kubelet uses its cached image; otherwise, the kubelet pulls the image with the resolved
    #             digest, and uses that image to launch the container.
    # "Never" => The kubelet does not try fetching the image. If the image is somehow already present locally, the
    #            kubelet attempts to start the container; otherwise, startup fails.
    #
    imagePullPolicy: "IfNotPresent"

    # -- Define image tag.
    tag: "stable-alpine3.23-slim@sha256:a00b591ab482fcfcc4a971a5efd04ebdbb6f9fe8ffe95dec9009019b8c0582e8"

  # Define and create Kubernetes Ingress.
  #
  # Ref.: https://kubernetes.io/docs/concepts/services-networking/ingress/
  ingress:
    # -- Enable creation of Ingress.
    enabled: true

    # -- Use default annotations for nginx, if set to false you probably need to specify your own annotations
    defaultAnnotations: true

    # -- Define the Fully Qualified Domain Name (FQDN) where application should be reachable.
    host: ""

    # -- Define the Ingress path.
    path: "/media/"

    # -- Each path in an Ingress is required to have a corresponding path type.
    # Paths that do not include an explicit pathType will fail validation.
    # There are three supported path types:
    #
    # "ImplementationSpecific" => With this path type, matching is up to the IngressClass. Implementations can treat this
    #                             as a separate pathType or treat it identically to Prefix or Exact path types.
    # "Exact" => Matches the URL path exactly and with case sensitivity.
    # "Prefix" => Matches based on a URL path prefix split by /.
    #
    # Ref.: https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types
    pathType: "Prefix"

    # -- The Ingress controller class name.
    ingressClassName: ""

    # -- Define custom ingress annotations.
    # annotations:
    #   nginx.ingress.kubernetes.io/rewrite-target: /
    annotations: {}

    # -- Secure an Ingress by specifying a Secret that contains a TLS private key and certificate.
    #
    # Ref.: https://kubernetes.io/docs/concepts/services-networking/ingress/#tls
    tls:
      # -- Enable TLS/SSL/HTTPS for Ingress.
      enabled: true

      # -- The name of the kubernetes secret which contains a TLS private key and certificate.
      # Hint: This secret is not created by this chart and must be provided.
      secretName: ""

  # -- Lifecycle to automate configuration before or after startup.
  lifecycleHooks: {}

  # -- Set nginx loglevel for Media Gateway
  #
  # Ref.: https://docs.nginx.com/nginx/admin-guide/monitoring/logging/
  loglevel: "debug"

  # -- Set nginx worker_processes for Media Gateway
  #
  # Ref.: https://nginx.org/en/docs/ngx_core_module.html#worker_processes
  workerProcesses: "4"

  # Configure resource requests and limits.
  #
  # Ref: https://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    limits:
      # -- The max number of CPUs to consume.
      cpu: 1
      # -- The max number of RAM to consume.
      memory: "512Gi"
    requests:
      # -- The number of CPUs which has to be available on the scheduled node.
      cpu: "100m"
      # -- The number of RAM which has to be available on the scheduled node.
      memory: "128Mi"

  # Define and create Kubernetes Service.
  #
  # Ref.: https://kubernetes.io/docs/concepts/services-networking/service
  service:
    # -- Additional custom annotations.
    annotations: {}

    # -- Enable kubernetes service creation.
    enabled: true

    # "ClusterIP" => Exposes the Service on a cluster-internal IP. Choosing this value makes the Service only reachable
    #                from within the cluster. This is the default that is used if you don't explicitly specify a type for
    #                a Service.
    # "NodePort" => Exposes the Service on each Node's IP at a static port (the NodePort). To make the node port
    #               available, Kubernetes sets up a cluster IP address, the same as if you had requested a Service of
    #               type: ClusterIP.
    # "LoadBalancer" => Exposes the Service externally using a cloud provider's load balancer.
    #
    # Ref.: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types

    # -- Choose the kind of Service, one of "ClusterIP", "NodePort" or "LoadBalancer".
    type: "ClusterIP"

    # Define the ports of Service.
    # You can set the port value to an arbitrary value, it will map the container port by name.
    #
    ports:
      http-gw:
        # -- Accessible port.
        port: 80
        # -- Internal port.
        containerPort: 8082
        # -- Service protocol.
        protocol: "TCP"

# Define and create Kubernetes Ingress.
#
# Ref.: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  # -- Enable creation of Ingress.
  enabled: true

  # -- Define the Fully Qualified Domain Name (FQDN) where application should be reachable.
  host: ""

  # -- Define the Ingress path.
  path: "/"

  # -- Each path in an Ingress is required to have a corresponding path type.
  # Paths that do not include an explicit pathType will fail validation.
  # There are three supported path types:
  #
  # "ImplementationSpecific" => With this path type, matching is up to the IngressClass. Implementations can treat this
  #                             as a separate pathType or treat it identically to Prefix or Exact path types.
  # "Exact" => Matches the URL path exactly and with case sensitivity.
  # "Prefix" => Matches based on a URL path prefix split by /.
  #
  # Ref.: https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types
  pathType: "Prefix"

  # -- The Ingress controller class name.
  ingressClassName: "nginx"

  # -- Define custom ingress annotations.
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /
  annotations: {}

  # -- Secure an Ingress by specifying a Secret that contains a TLS private key and certificate.
  #
  # Ref.: https://kubernetes.io/docs/concepts/services-networking/ingress/#tls
  tls:
    # -- Enable TLS/SSL/HTTPS for Ingress.
    enabled: true

    # -- The name of the kubernetes secret which contains a TLS private key and certificate.
    # Hint: This secret is not created by this chart and must be provided.
    secretName: ""

# -- Lifecycle to automate configuration before or after startup.
lifecycleHooks: {}

# -- String to partially override release name.
nameOverride: ""

# -- Node labels for pod assignment.
# Ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}

# -- Pod disruption budget
# Ref.: https://kubernetes.io/docs/tasks/run-application/configure-pdb/
pdb:
  # -- Whether PodDisruptionBudget for the frontend should be enabled
  enabled: true
  # -- How many pods need to be available at any given time
  minAvailable: 1
  # -- How many pods can be unavailable at any given time
  maxUnavailable: ~

# -- Pod Annotations.
# Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}

# -- Pod Labels.
# Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

# Pod Security Context.
# Ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
podSecurityContext:
  # -- Enable security context.
  enabled: true

  # -- If specified, all processes of the container are also part of the supplementary group.
  fsGroup: 1000

  # -- Change ownership and permission of the volume before being exposed inside a Pod.
  fsGroupChangePolicy: "Always"

# -- Set the amount of replicas of deployment.
replicaCount: 1

# Configure resource requests and limits.
#
# Ref: https://kubernetes.io/docs/user-guide/compute-resources/
resources:
  limits:
    # -- The max number of CPUs to consume.
    cpu: 1
    # -- The max number of RAM to consume.
    memory: "1Gi"
  requests:
    # -- The number of CPUs which has to be available on the scheduled node.
    cpu: "100m"
    # -- The number of RAM which has to be available on the scheduled node.
    memory: "512Mi"

# Define and create Kubernetes Service.
#
# Ref.: https://kubernetes.io/docs/concepts/services-networking/service
service:
  # -- Additional custom annotations.
  annotations: {}

  # -- Enable kubernetes service creation.
  enabled: true

  # "ClusterIP" => Exposes the Service on a cluster-internal IP. Choosing this value makes the Service only reachable
  #                from within the cluster. This is the default that is used if you don't explicitly specify a type for
  #                a Service.
  # "NodePort" => Exposes the Service on each Node's IP at a static port (the NodePort). To make the node port
  #               available, Kubernetes sets up a cluster IP address, the same as if you had requested a Service of
  #               type: ClusterIP.
  # "LoadBalancer" => Exposes the Service externally using a cloud provider's load balancer.
  #
  # Ref.: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types

  # -- Choose the kind of Service, one of "ClusterIP", "NodePort" or "LoadBalancer".
  type: "ClusterIP"

  # Define the ports of Service.
  # You can set the port value to an arbitrary value, it will map the container port by name.
  #
  ports:
    http:
      # -- Accessible port.
      port: 80
      # -- Internal port.
      containerPort: 8080
      # -- Service protocol.
      protocol: "TCP"

# Service account to use.
# Ref.: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
serviceAccount:
  # -- Additional custom annotations for the ServiceAccount.
  annotations: {}

  # -- Allows auto mount of ServiceAccountToken on the serviceAccount created. Can be set to false if pods using this
  # serviceAccount do not need to use K8s API.
  automountServiceAccountToken: false

  # -- Enable creation of ServiceAccount for pod.
  create: true

  # -- Additional custom labels for the ServiceAccount.
  labels: {}

# -- In seconds, time the given to the pod needs to terminate gracefully.
# Ref: https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods
terminationGracePeriodSeconds: ""

# -- Tolerations for pod assignment.
# Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

# -- Topology spread constraints rely on node labels to identify the topology domain(s) that each Node is in.
# Ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/
#
# topologySpreadConstraints:
#   - maxSkew: 1
#     topologyKey: failure-domain.beta.kubernetes.io/zone
#     whenUnsatisfiable: DoNotSchedule
topologySpreadConstraints: []

# Set up update strategy.
#
# Ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
#
# Example:
# updateStrategy:
#  type: RollingUpdate
#  rollingUpdate:
#    maxSurge: 25%
#    maxUnavailable: 25%
updateStrategy:
  # -- Set to Recreate if you use persistent volume that cannot be mounted by more than one pods to make sure the pods
  # are destroyed first.
  type: "RollingUpdate"

configuration:
  # -- Internal backend service hostname (Kubernetes service DNS name, e.g. "impress-backend")
  backendHost: "impress-backend"
  # -- Internal backend service port
  backendPort: 80
  # -- Object Store Host
  objectStoreHost: ""
  # -- Object Store Port
  objectStorePort: 443
  # -- Object Store Bucket name
  objectStoreBucketName: "notes"
  # -- Container port to listen on
  port: 8080
...
