{{/*
SPDX-FileCopyrightText: 2025 Zentrum für Digitale Souveränität der Öffentlichen Verwaltung (ZenDiS) GmbH
SPDX-License-Identifier: Apache-2.0
*/}}
{{- if or .Values.configuration.init.migrate.enabled .Values.configuration.init.createSuperuser.enabled }}
---
apiVersion: {{ include "common.capabilities.cronjob.apiVersion" . | quote }}
kind: "Job"
metadata:
  name: "{{ include "common.names.fullname" . }}-init"
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "post-install"
    "argocd.argoproj.io/sync-options": "Replace=true,Force=true"
spec:
  {{- if .Values.cleanup.deletePodsOnSuccess }}
  ttlSecondsAfterFinished: {{ .Values.cleanup.deletePodsOnSuccessTimeout }}
  {{- end }}
  template:
    metadata:
      annotations:
        {{- if .Values.podAnnotationsInit }}
        {{- include "common.tplvalues.render" (dict "value" .Values.podAnnotationsInit "context" .) | nindent 8 }}
        {{- end }}
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
    spec:
      {{- if or .Values.imagePullSecrets .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
        - name: "{{ . }}"
        {{- end }}
        {{- range .Values.imagePullSecrets }}
        - name: "{{ . }}"
        {{- end }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.affinity "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.nodeSelector "context" .) | nindent 8 }}
      {{- end }}
      restartPolicy: {{ .Values.configuration.init.restartPolicy }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "common.names.fullname" . }}
      {{- end }}
      {{- if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- end }}
      containers:
        - name: {{ include "common.names.fullname" . | quote }}
          {{- if .Values.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          image: "{{ coalesce .Values.image.registry .Values.global.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          command:
            - "/bin/sh"
            - "-c"
            - |
              while ! python manage.py check --database default > /dev/null 2>&1
              do
                echo "Database not ready"
                sleep 2
              done
              {{- if .Values.configuration.init.migrate.enabled }}
              {{ .Values.configuration.init.migrate.command }}
              {{- end }}
              {{- if .Values.configuration.init.createSuperuser.enabled }}
              {{ .Values.configuration.init.createSuperuser.command }}
              {{- end }}
          env:
            {{- if .Values.configuration.database.engine }}
            - name: "DB_ENGINE"
              value: {{ .Values.configuration.database.engine | quote }}
            {{- end }}
            - name: "DB_NAME"
              value: {{ .Values.configuration.database.name | quote }}
            - name: "DB_USER"
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.configuration.database.user.existingSecret.name | default (include "common.names.fullname" .) | quote }}
                  key: {{ .Values.configuration.database.user.existingSecret.key | default "dbUser" | quote }}
            - name: "DB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.configuration.database.password.name | default (include "common.names.fullname" .) | quote }}
                  key: {{ .Values.configuration.database.password.key | default "dbPassword" | quote }}
            - name: "DB_HOST"
              value: {{ .Values.configuration.database.host | quote }}
            - name: "DB_PORT"
              value: {{ .Values.configuration.database.port | quote }}
            - name: "REDIS_URL"
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.configuration.redisUrl.existingSecret.name | default (include "common.names.fullname" .) | quote }}
                  key: {{ .Values.configuration.redisUrl.existingSecret.key | default "redisUrl" | quote }}
            - name: "DJANGO_CSRF_TRUSTED_ORIGINS"
              value: {{ .Values.configuration.django.csrfTrustedOrigins | default (printf "https://%s" .Values.global.fqdn) | quote }}
            - name: "DJANGO_SITE_DOMAIN"
              value: {{ .Values.configuration.django.siteDomain | default .Values.global.fqdn | quote }}
            - name: "DJANGO_SITE_NAME"
              value: {{ .Values.configuration.django.siteName | default .Values.global.fqdn | quote }}
            - name: "DJANGO_CONFIGURATION"
              value: {{ .Values.configuration.django.configuration | default "Production" | quote }}
            - name: "DJANGO_ALLOWED_HOSTS"
              value: {{ .Values.configuration.django.allowedHosts | quote }}
            - name: "DJANGO_SECRET_KEY"
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.configuration.django.secretKey.existingSecret.name | default (include "common.names.fullname" .) | quote }}
                  key: {{ .Values.configuration.django.secretKey.existingSecret.key | default "djangoSecretKey" | quote }}
            - name: "DJANGO_SETTINGS_MODULE"
              value: {{ .Values.configuration.django.settingsModule | quote }}
            - name: "DJANGO_SUPERUSER_EMAIL"
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.configuration.django.superuserEmail.existingSecret.name | default (include "common.names.fullname" .) | quote }}
                  key: {{ .Values.configuration.django.superuserEmail.existingSecret.key | default "djangoSuperuserEmail" | quote }}
            - name: "DJANGO_SUPERUSER_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.configuration.django.superuserPassword.existingSecret.name | default (include "common.names.fullname" .) | quote }}
                  key: {{ .Values.configuration.django.superuserPassword.existingSecret.key | default "djangoSuperuserPassword" | quote }}
            - name: "DJANGO_EMAIL_BRAND_NAME"
              value: {{ .Values.configuration.email.brandName | quote }}
            - name: "DJANGO_EMAIL_LOGO_IMG"
              value: {{ .Values.configuration.email.logoImage | quote }}
            - name: "DJANGO_EMAIL_FROM"
              value: {{ .Values.configuration.email.from | quote }}
            - name: "DJANGO_EMAIL_HOST"
              value: {{ .Values.configuration.email.host | quote }}
            - name: "DJANGO_EMAIL_PORT"
              value: {{ .Values.configuration.email.port | quote }}
            - name: "DJANGO_EMAIL_USE_SSL"
              value: {{ .Values.configuration.email.useSSL | quote }}
            - name: "DJANGO_EMAIL_HOST_USER"
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.configuration.email.user.existingSecret.name | default (include "common.names.fullname" .) | quote }}
                  key: {{ .Values.configuration.email.user.existingSecret.key | default "djangoEmailHostUser" | quote }}
            - name: "DJANGO_EMAIL_HOST_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.configuration.email.password.existingSecret.name | default (include "common.names.fullname" .) | quote }}
                  key: {{ .Values.configuration.email.password.existingSecret.key | default "djangoEmailHostPassword" | quote }}
            - name: "DJANGO_EMAIL_USE_TLS"
              value: {{ .Values.configuration.email.useTLS | quote }}
            - name: "AI_API_KEY"
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.configuration.ai.apiKey.existingSecret.name | default (include "common.names.fullname" .) | quote }}
                  key: {{ .Values.configuration.ai.apiKey.existingSecret.key | default "aiApiKey" | quote }}
            - name: "AI_BASE_URL"
              value: {{ .Values.configuration.ai.baseUrl | quote }}
            - name: "AI_MODEL"
              value: {{ .Values.configuration.ai.model | quote }}
            - name: "AI_ALLOW_REACH_FROM"
              value: {{ .Values.configuration.ai.allowReachFrom | quote }}
            - name: "AWS_S3_ENDPOINT_URL"
              value: {{ .Values.configuration.aws.endpointUrl | quote }}
            - name: "AWS_S3_ACCESS_KEY_ID"
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.configuration.aws.s3AccessKeyId.existingSecret.name | default (include "common.names.fullname" .) | quote }}
                  key: {{ .Values.configuration.aws.s3AccessKeyId.existingSecret.key | default "awsS3AccessKeyId" | quote }}
            - name: "AWS_S3_SECRET_ACCESS_KEY"
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.configuration.aws.s3SecretAccessKey.existingSecret.name | default (include "common.names.fullname" .) | quote }}
                  key: {{ .Values.configuration.aws.s3SecretAccessKey.existingSecret.key | default "awsS3SecretAccessKey" | quote }}
            - name: "AWS_S3_REGION_NAME"
              value: {{ .Values.configuration.aws.regionName | quote }}
            - name: "AWS_STORAGE_BUCKET_NAME"
              value: {{ .Values.configuration.aws.storageBucketName | quote }}
            {{- if .Values.configuration.oidc.enabled }}
            - name: "OIDC_CREATE_USER"
              value: {{ .Values.configuration.oidc.createUser | quote }}
            - name: "OIDC_RP_SIGN_ALGO"
              value: {{ .Values.configuration.oidc.rpSignAlgo | quote }}
            - name: "OIDC_RP_CLIENT_ID"
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.configuration.oidc.rpClientId.existingSecret.name | default (include "common.names.fullname" .) | quote }}
                  key: {{ .Values.configuration.oidc.rpClientId.existingSecret.key | default "oidcRpClientId" | quote }}
            - name: "OIDC_RP_CLIENT_SECRET"
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.configuration.oidc.rpClientSecret.existingSecret.name | default (include "common.names.fullname" .) | quote }}
                  key: {{ .Values.configuration.oidc.rpClientSecret.existingSecret.key | default "oidcRpClientSecret" | quote }}
            - name: "OIDC_OP_JWKS_ENDPOINT"
              value: {{ .Values.configuration.oidc.opJWKSEndpoint | quote }}
            - name: "OIDC_OP_AUTHORIZATION_ENDPOINT"
              value: {{ .Values.configuration.oidc.opAuthorizationEndpoint | quote }}
            - name: "OIDC_OP_TOKEN_ENDPOINT"
              value: {{ .Values.configuration.oidc.opTokenEndpoint | quote }}
            - name: "OIDC_OP_USER_ENDPOINT"
              value: {{ .Values.configuration.oidc.opUserEndpoint | quote }}
            - name: "OIDC_OP_LOGOUT_ENDPOINT"
              value: {{ .Values.configuration.oidc.opLogoutEndpoint | quote }}
            - name: "OIDC_AUTH_REQUEST_EXTRA_PARAMS"
              value: {{ .Values.configuration.oidc.authRequestExtraParams | quote }}
            - name: "OIDC_RP_SCOPES"
              value: {{ .Values.configuration.oidc.rpScopes | quote }}
            - name: "LOGIN_REDIRECT_URL"
              value: {{ .Values.configuration.oidc.loginRedirectUrl | quote }}
            - name: "LOGIN_REDIRECT_URL_FAILURE"
              value: {{ .Values.configuration.oidc.loginRedirectUrlFailure | quote }}
            - name: "LOGOUT_REDIRECT_URL"
              value: {{ .Values.configuration.oidc.logoutRedirectUrl | quote }}
            - name: "OIDC_USE_NONCE"
              value: {{ .Values.configuration.oidc.useNonce | quote }}
            - name: "OIDC_REDIRECT_REQUIRE_HTTPS"
              value: {{ .Values.configuration.oidc.redirectRequireHTTPS | quote }}
            - name: "OIDC_REDIRECT_ALLOWED_HOSTS"
              value: {{ .Values.configuration.oidc.redirectAllowedHosts | quote }}
            - name: "OIDC_STORE_ID_TOKEN"
              value: {{ .Values.configuration.oidc.storeIDToken | quote }}
            - name: "OIDC_FALLBACK_TO_EMAIL_FOR_IDENTIFICATION"
              value: {{ .Values.configuration.oidc.fallbackToEmailForIdentification | quote }}
            - name: "OIDC_ALLOW_DUPLICATE_EMAILS"
              value: {{ .Values.configuration.oidc.allowDuplicateEmails | quote }}
            - name: "USER_OIDC_ESSENTIAL_CLAIMS"
              value: {{ .Values.configuration.oidc.essentialClaims | quote }}
            - name: "OIDC_USERINFO_FULLNAME_FIELDS"
              value: {{ .Values.configuration.oidc.fullnameFields | quote }}
            - name: "OIDC_USERINFO_SHORTNAME_FIELD"
              value: {{ .Values.configuration.oidc.shortnameField | quote }}
            - name: "ALLOW_LOGOUT_GET_METHOD"
              value: {{ .Values.configuration.oidc.allowLogoutGetMethod | quote }}
            {{- end }}
            - name: "Y_PROVIDER_API_KEY"
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.yProviderApiKey.existingSecret.name | default (include "common.names.fullname" .) | quote }}
                  key: {{ .Values.global.yProviderApiKey.existingSecret.key | default "yProviderApiKey" | quote }}
            - name: "Y_PROVIDER_API_BASE_URL"
              value: {{ .Values.configuration.yProvider.apiBaseUrl | default (printf "https://%s/api/" .Values.global.fqdn) | quote }}
            - name: "COLLABORATION_API_URL"
              value: {{ .Values.configuration.collaboration.apiUrl | quote }}
            - name: "COLLABORATION_SERVER_SECRET"
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.collaborationServerSecret.existingSecret.name | default (include "common.names.fullname" .) | quote }}
                  key: {{ .Values.global.collaborationServerSecret.existingSecret.key | default "collaborationServerSecret" | quote }}
            - name: "COLLABORATION_WS_URL"
              value: {{ .Values.configuration.collaboration.wsUrl | quote }}
            - name: "FRONTEND_THEME"
              value: {{ .Values.configuration.frontendTheme | quote }}
            - name: "MEDIA_BASE_URL"
              value: {{ .Values.configuration.mediaBaseUrl | quote }}
            {{- if .Values.configuration.documentImageMaxSize }}
            - name: "DOCUMENT_IMAGE_MAX_SIZE"
              value: {{ .Values.configuration.documentImageMaxSize | quote }}
            {{- end }}
            - name: "TRASHBIN_CUTOFF_DAYS"
              value: {{ .Values.configuration.trashbinCutoffDays | quote }}
          {{- with .Values.extraEnvVars }}
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.resources }}
          resources: {{- include "common.tplvalues.render" (dict "value" .Values.resources "context" .) | nindent 12 }}
          {{- end }}
          {{- if .Values.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.lifecycleHooks "context" .) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: "tmp"
              mountPath: "/tmp"
            {{- if .Values.extraVolumeMounts }}
            {{- include "common.tplvalues.render" (dict "value" .Values.extraVolumeMounts "context" .) | nindent 12 }}
            {{- end }}
      volumes:
        - name: "tmp"
          emptyDir: {}
        {{- if .Values.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.extraVolumes  "context" .) | nindent 8 }}
        {{- end }}
...
{{- end }}
