{{/*
SPDX-FileCopyrightText: 2025 Zentrum für Digitale Souveränität der Öffentlichen Verwaltung (ZenDiS) GmbH
SPDX-License-Identifier: Apache-2.0
*/}}
{{- if or (not .Values.global.collaborationServerSecret.existingSecret.name)
          (not .Values.global.yProviderApiKey.existingSecret.name)
          (not .Values.global.s3.accessKeyId.existingSecret.name)
          (not .Values.global.s3.secretAccessKey.existingSecret.name)
          (not .Values.configuration.database.user.existingSecret.name)
          (not .Values.configuration.database.password.existingSecret.name)
          (not .Values.configuration.django.secretKey.existingSecret.name)
          (not .Values.configuration.django.superuserEmail.value)
          (not .Values.configuration.django.superuserPassword.existingSecret.name)
          (not .Values.configuration.email.user.existingSecret.name)
          (not .Values.configuration.email.password.existingSecret.name)
          (not .Values.configuration.ai.apiKey.existingSecret.name)
          (not .Values.configuration.oidc.rpClientId.existingSecret.name)
          (not .Values.configuration.oidc.rpClientSecret.existingSecret.name)
          (not .Values.configuration.redisUrl.existingSecret.name)
          }}
---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ include "common.names.fullname" . | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.additionalLabels "context" . ) | nindent 4 }}
    {{- end }}
  {{- if .Values.additionalAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}
stringData:
  collaborationServerSecret: {{ .Values.global.collaborationServerSecret.value | quote }}
  yProviderApiKey: {{ .Values.global.yProviderApiKey.value | quote }}
  dbUser: {{ .Values.configuration.database.user.value | quote }}
  dbPassword: {{ .Values.configuration.database.password.value | quote }}
  djangoSecretKey: {{ .Values.configuration.django.secretKey.value | quote }}
  djangoSuperuserEmail: {{ .Values.configuration.django.superuserEmail.value | quote  }}
  djangoSuperuserPassword: {{ .Values.configuration.django.superuserPassword.value | quote  }}
  djangoEmailHostUser: {{ .Values.configuration.email.user.value | quote }}
  djangoEmailHostPassword: {{ .Values.configuration.email.password.value | quote }}
  aiApiKey: {{ .Values.configuration.ai.apiKey.value | quote }}
  awsS3AccessKeyId: {{ .Values.global.s3.accessKeyId.value | quote }}
  awsS3SecretAccessKey: {{ .Values.global.s3.secretAccessKey.value | quote }}
  oidcRpClientId: {{ .Values.configuration.oidc.rpClientId.value | quote }}
  oidcRpClientSecret: {{ .Values.configuration.oidc.rpClientSecret.value | quote }}
  redisUrl: {{ .Values.configuration.redisUrl.value | quote }}
...
{{- end }}
