{{/*
SPDX-FileCopyrightText: 2025-2026 Zentrum für Digitale Souveränität der Öffentlichen Verwaltung (ZenDiS) GmbH
SPDX-License-Identifier: Apache-2.0
*/}}
{{- if .Values.impressMediaGateway.ingress.enabled -}}
---
apiVersion: "{{ include "common.capabilities.ingress.apiVersion" . }}"
kind: "Ingress"
metadata:
  name: "{{ include "common.names.fullname" . }}-media"
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.additionalLabels "context" . ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.impressMediaGateway.ingress.defaultAnnotations }}
    haproxy-ingress.github.io/backend-protocol: "h1"
    {{- end }}
    {{- if .Values.additionalAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.additionalAnnotations "context" . ) | nindent 4 }}
    {{- end }}
    {{- if .Values.impressMediaGateway.ingress.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.impressMediaGateway.ingress.annotations "context" . ) | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.impressMediaGateway.ingress.ingressClassName }}
  ingressClassName: {{ .Values.impressMediaGateway.ingress.ingressClassName | quote }}
  {{- end }}
  {{- if .Values.impressMediaGateway.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ coalesce .Values.impressMediaGateway.ingress.host .Values.global.fqdn | quote }}
      secretName: "{{ coalesce .Values.impressMediaGateway.ingress.tls.secretName .Values.global.tlsSecretName | default (printf "%s-tls" (include "common.names.fullname" . )) }}"
  {{- end }}
  rules:
    - host: {{ coalesce .Values.impressMediaGateway.ingress.host .Values.global.fqdn | quote }}
      http:
        paths:
          - path: {{ .Values.impressMediaGateway.ingress.path }}
            pathType: {{ .Values.impressMediaGateway.ingress.pathType }}
            backend:
              service:
                name: "{{ include "common.names.fullname" . }}-mediagateway"
                port:
                  number: 80
...
{{- end }}
