{{/*
SPDX-FileCopyrightText: 2025 Zentrum für Digitale Souveränität der Öffentlichen Verwaltung (ZenDiS) GmbH
SPDX-License-Identifier: Apache-2.0
*/}}
{{- if .Values.ingressMedia.enabled -}}
---
apiVersion: "{{ include "common.capabilities.ingress.apiVersion" . }}"
kind: "Ingress"
metadata:
  name: "{{ include "common.names.fullname" . }}-media"
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.additionalLabels "context" . ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.ingressMedia.defaultAnnotations }}
    nginx.ingress.kubernetes.io/auth-response-headers: "Authorization, X-Amz-Date, X-Amz-Content-SHA256"
    nginx.ingress.kubernetes.io/auth-url: {{ printf "https://%s/api/v1.0/documents/media-auth/" .Values.global.fqdn | quote }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/rewrite-target: {{ printf "/%s/$1" .Values.configuration.objectStoreBucketName | quote }}
    nginx.ingress.kubernetes.io/session-cookie-path: "/media"
    nginx.ingress.kubernetes.io/upstream-vhost: {{ .Values.configuration.objectStoreHost | quote }}
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- end }}
    {{- if .Values.additionalAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.additionalAnnotations "context" . ) | nindent 4 }}
    {{- end }}
    {{- if .Values.ingressMedia.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.ingressMedia.annotations "context" . ) | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingressMedia.ingressClassName }}
  ingressClassName: {{ .Values.ingressMedia.ingressClassName | quote }}
  {{- end }}
  {{- if .Values.ingressMedia.tls.enabled }}
  tls:
    - hosts:
        - {{ coalesce .Values.ingressMedia.host .Values.global.fqdn | quote }}
      secretName: "{{ coalesce .Values.ingressMedia.tls.secretName .Values.global.tlsSecretName | default (printf "%s-tls" (include "common.names.fullname" . )) }}"
  {{- end }}
  rules:
    - host: {{ coalesce .Values.ingressMedia.host .Values.global.fqdn | quote }}
      http:
        paths:
          - path: {{ .Values.ingressMedia.path }}
            pathType: {{ .Values.ingressMedia.pathType }}
            backend:
              service:
                name: "{{ include "common.names.fullname" . }}-media"
                port:
                  number: {{ .Values.serviceMedia.port }}
...
{{- end }}
